server:
  port: 8090
  error:
    include-message: always

spring:
  application:
    name: training-service

  data:
    mongodb:
      database: training
      uri: mongodb://root:123456@localhost:27017/training?authSource=admin

  devtools:
    add-properties: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    basic:
      enable: false

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: group-1

logging:
  level:
    root: info
  file:
    path: logs
    max-size: 10KB
    max-history: 7

app:
  jwt:
    secret_key: t#8MR6r$@Q3x
    expiration: 604800000
