server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: training-service
  jpa:
    generate-ddl: true
    database: postgresql
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/training
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver
    initialize: true

  devtools:
    add-properties: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    basic:
      enable: false

logging:
  level:
    root: info
  file:
    path: logs
    max-size: 10KB
    max-history: 7

app:
  jwt:
    secret_key: t#8MR6r$@Q3x
    expiration: 604800000
