server:
  port: 8090
  error:
    include-message: always

spring:
  application:
    name: training-service
  jpa:
    generate-ddl: true
    database: postgresql
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://host.docker.internal:5555/training
#    url: jdbc:postgresql://localhost:5432/training
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver
    initialize: true
  
  data:
    mongodb:
      user: root
      password: 123456
      database: training
      uri: mongodb://root:123456@host.docker.internal:27017/training?authSource=admin

  devtools:
    add-properties: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    basic:
      enable: false

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: group-1

logging:
  level:
    root: info
  file:
    path: logs
    max-size: 10KB
    max-history: 7

app:
  jwt:
    secret_key: t#8MR6r$@Q3x
    expiration: 604800000
